#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: The Introverted Developer

# Short bio or description (displayed in the header)
description: A place for introverted developers to share experiences and learn to make the most of their introversion.

# Default author information
author:
  name: The Introverted Developer
  avatar: https://avatars1.githubusercontent.com/u/32388982
  twitter: theintdev
  url: https://www.theintdev.com
  bio: A place for introverted developers to share experiences and learn to make the most of their introversion.

#
# Flags below are optional
#

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: theintdev

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-107343447-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.theintdev.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Your github repository name
repository: "theintdev/theintdev.github.io"

# Define the number of posts to display per page
paginate: 12

#
# !! You don't need to change any of the configuration flags below !!
#
github: [metadata]

permalink: pretty

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Disable the syntax highlighter
  syntax_highlighter_opts:
    disable: true

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate # Allow pagination of collections
  - jekyll-redirect-from # Redirect from old url structure

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - run.bat
  - run_draft.bat
